export const APP_LOAD = "APP_LOD";

export const LOGOUT = "LOGOUT";
export const FETCH_REGISTER_REQ = "FETCH_REGISTER_REQ";
export const FETCH_REGISTER_ERROR = "FETCH_REGISTER_ERROR";
export const FETCH_REGISTER_SUCCESS = "FETCH_REGISTER_SUCCESS";

export const FETCH_LOGIN_REQ = "FETCH_LOGIN_REQ";
export const FETCH_LOGIN_ERROR = "FETCH_LOGIN_ERROR";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const REGISTER_UNLOAD = "AUTH_UNLOAD";
export const LOGIN_UNLOAD = "AUTH_UNLOAD";

export const FETCH_SESSION_DATA_SUCCESS = "FETCH_SESSION_DATA_SUCCESS";


export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const FETCH_USERS_REQ = "FETCH_USERS_REQ";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";